#!/bin/bash -e

configfs_init()
{
    modprobe libcomposite

    mkdir -p "/sys/kernel/config/usb_gadget/radxa-otgutils"
    pushd "/sys/kernel/config/usb_gadget/radxa-otgutils"

    echo "0x1d6b" > "idVendor"  # Linux Foundation
    echo "0x0104" > "idProduct" # Multifunction Composite Gadget
    echo "0x0100" > "bcdDevice" # v1.0.0
    echo "0x0200" > "bcdUSB"    # USB 2.0
    echo "0xEF" > "bDeviceClass"
    echo "0x02" > "bDeviceSubClass"
    echo "0x01" > "bDeviceProtocol"

    mkdir -p "strings/0x409"
    echo "0123456789ABCDEF" > "strings/0x409/serialnumber"
    echo "Radxa" > "strings/0x409/manufacturer"
    echo "OTG Utils" > "strings/0x409/product"

    mkdir -p "configs/r.1/strings/0x409"
    echo "500" > "configs/r.1/MaxPower"
    echo "adb" > "configs/r.1/strings/0x409/configuration"

    popd
}

function_init()
{
    case "$MODE" in
        adbd)
            local GADGET="ffs.adb"
            ;;
        usbnet)
            local GADGET="ecm.usb0"
            ;;
    esac

    if [ ! -e "/sys/kernel/config/usb_gadget/radxa-otgutils/functions/$GADGET" ];
    then
        mkdir -p "/sys/kernel/config/usb_gadget/radxa-otgutils/functions/$GADGET"
    fi

    if [ ! -e "/sys/kernel/config/usb_gadget/radxa-otgutils/configs/r.1/$GADGET" ];
    then
        ln -s "/sys/kernel/config/usb_gadget/radxa-otgutils/functions/$GADGET" "/sys/kernel/config/usb_gadget/radxa-otgutils/configs/r.1/$GADGET"
    fi
}

function_stop()
{
    case "$MODE" in
        adbd)
            local GADGET="ffs.adb"
            ;;
        usbnet)
            local GADGET="ecm.usb0"
            ;;
    esac

    if [ -e "/sys/kernel/config/usb_gadget/radxa-otgutils/configs/r.1/$GADGET" ];
    then
        rm "/sys/kernel/config/usb_gadget/radxa-otgutils/configs/r.1/$GADGET"
    fi

    if [ -e "/sys/kernel/config/usb_gadget/radxa-otgutils/functions/$GADGET" ];
    then
        rmdir "/sys/kernel/config/usb_gadget/radxa-otgutils/functions/$GADGET"
    fi
}

start()
{
    configfs_init
    function_init

    case "$MODE" in
        adbd)
            if [ ! -e "/dev/usb-ffs/adb" ] ;
            then
                mkdir -p /dev/usb-ffs/adb
                mount -o uid=2000,gid=2000 -t functionfs adb /dev/usb-ffs/adb
            fi
            export service_adb_tcp_port=5555
            start-stop-daemon --start --oknodo --pidfile /var/run/adbd.pid --startas /usr/bin/adbd --background
            sleep 1
            ;;
    esac

    local UDC=
    UDC="$(basename "$(find /sys/class/udc -maxdepth 1 -mindepth 1 | sort | head -1)")"
    if [ -z "$UDC" ]; 
    then
        echo "No USB Device Controller was detected. Did you set your OTG port to host mode?"
        exit 1
    fi
    echo "$UDC" > "/sys/kernel/config/usb_gadget/radxa-otgutils/UDC" || true
}

stop()
{
    function_stop

    case "$MODE" in
        adbd)
            start-stop-daemon --stop --oknodo --pidfile /var/run/adbd.pid --retry 5
            umount /dev/usb-ffs/adb
            rmdir /dev/usb-ffs/adb
            rmdir /dev/usb-ffs
            ;;
    esac
}

MODE=
case "$(basename "$0")" in
    radxa-adbd)
        if ! command -v adbd
        then
            echo "Did not find adbd. Please check if related packages are installed."
            exit 1
        fi
        MODE=adbd
        ;;
    radxa-usbnet)
        MODE=usbnet
        ;;
    radxa-otgutils)
        echo Please run this script from symbolic links.
        exit 1
        ;;
    *)
        echo Unknown script name.
        exit 1
        ;;
esac

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart|reload)
    stop
    start
    ;;
*)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
