#!/bin/bash -e

configfs_init()
{
    modprobe libcomposite

    case "$MODE" in
        adbd)
            local VENDOR="0x18d1"
            local PRODUCT="0x0001"
            ;;
        usbnet)
            local VENDOR="0x1d6b"
            local PRODUCT="0x0104"
            ;;
    esac

    mkdir -p "/sys/kernel/config/usb_gadget/radxa-$MODE"
    chmod 0770 "/sys/kernel/config/usb_gadget/radxa-$MODE"
    echo "$VENDOR" > "/sys/kernel/config/usb_gadget/radxa-$MODE/idVendor"
    echo "$PRODUCT" > "/sys/kernel/config/usb_gadget/radxa-$MODE/idProduct"
    mkdir -p "/sys/kernel/config/usb_gadget/radxa-$MODE/strings/0x409"
    chmod 0770 "/sys/kernel/config/usb_gadget/radxa-$MODE/strings/0x409"
    echo "Radxa" > "/sys/kernel/config/usb_gadget/radxa-$MODE/strings/0x409/manufacturer"
    echo "$MODE" > "/sys/kernel/config/usb_gadget/radxa-$MODE/strings/0x409/product"
    mkdir -p "/sys/kernel/config/usb_gadget/radxa-$MODE/configs/r.1"
    chmod 0770 "/sys/kernel/config/usb_gadget/radxa-$MODE/configs/r.1"

    case "$MODE" in
        adbd)
            echo "0123456789ABCDEF" > "/sys/kernel/config/usb_gadget/radxa-$MODE/strings/0x409/serialnumber"
            mkdir -p "/sys/kernel/config/usb_gadget/radxa-$MODE/configs/r.1/strings/0x409"
            chmod 0770 "/sys/kernel/config/usb_gadget/radxa-$MODE/configs/r.1/strings/0x409"
            echo "500" > "/sys/kernel/config/usb_gadget/radxa-$MODE/configs/r.1/MaxPower"
            echo "adb" > "/sys/kernel/config/usb_gadget/radxa-$MODE/configs/r.1/strings/0x409/configuration"
            ;;
    esac
}

function_stop()
{
    case "$MODE" in
        adbd)
            local GADGET="ffs.adb"
            ;;
        usbnet)
            local GADGET="ecm.usb0"
            ;;
    esac

    if [ -e "/sys/kernel/config/usb_gadget/radxa-otgutils/configs/r.1/$GADGET" ];
    then
        rm "/sys/kernel/config/usb_gadget/radxa-otgutils/configs/r.1/$GADGET"
    fi
}

start()
{
    configfs_init
    function_init

    case "$MODE" in
        adbd)
            if [ ! -e "/dev/usb-ffs/adb" ] ;
            then
                mkdir -p /dev/usb-ffs/adb
                mount -o uid=2000,gid=2000 -t functionfs adb /dev/usb-ffs/adb
            fi
            export service_adb_tcp_port=5555
            start-stop-daemon --start --oknodo --pidfile /var/run/adbd.pid --startas /usr/bin/adbd --background
            sleep 1
            ;;
    esac

    local UDC=
    UDC="$(basename "$(find /sys/class/udc -maxdepth 1 -mindepth 1 | sort | head -1)")"
    if [ -z "$UDC" ]; 
    then
        echo "No USB Device Controller was detected. Did you set your OTG port to host mode?"
        exit 1
    fi
    echo "$UDC" > "/sys/kernel/config/usb_gadget/radxa-$MODE/UDC"
}

stop()
{
    echo "none" > "/sys/kernel/config/usb_gadget/radxa-$MODE/UDC"
    case "$MODE" in
        adbd)
            start-stop-daemon --stop --oknodo --pidfile /var/run/adbd.pid --retry 5
            ;;
    esac
}

MODE=
case "$(basename "$0")" in
    radxa-adbd)
        if ! command -v adbd
        then
            echo "Did not find adbd. Please check if related packages are installed."
            exit 1
        fi
        MODE=adbd
        ;;
    radxa-usbnet)
        MODE=usbnet
        ;;
    radxa-otgutils)
        echo Please run this script from symbolic links.
        exit 1
        ;;
    *)
        echo Unknown script name.
        exit 1
        ;;
esac

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart|reload)
    stop
    start
    ;;
*)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
