#!/bin/bash -e

configfs_init()
{
    modprobe libcomposite

    mkdir -p "/sys/kernel/config/usb_gadget/$UDC"
    pushd "/sys/kernel/config/usb_gadget/$UDC"

    echo "0x1d6b" > "idVendor"  # Linux Foundation
    echo "0x0104" > "idProduct" # Multifunction Composite Gadget
    echo "0x0100" > "bcdDevice" # v1.0.0
    echo "0x0200" > "bcdUSB"    # USB 2.0
    echo "0xEF" > "bDeviceClass"
    echo "0x02" > "bDeviceSubClass"
    echo "0x01" > "bDeviceProtocol"

    mkdir -p "strings/0x409"
    echo "0123456789ABCDEF" > "strings/0x409/serialnumber"
    echo "Radxa" > "strings/0x409/manufacturer"
    echo "OTG Utils" > "strings/0x409/product"

    mkdir -p "configs/r.1/strings/0x409"
    echo "500" > "configs/r.1/MaxPower"
    echo "adb" > "configs/r.1/strings/0x409/configuration"

    popd
}

function_init()
{
    case "$MODE" in
        adbd)
            local GADGET="ffs.adb"
            ;;
        usbnet)
            local GADGET="ecm.usb0"
            ;;
    esac

    if [ ! -e "/sys/kernel/config/usb_gadget/$UDC/functions/$GADGET" ];
    then
        mkdir -p "/sys/kernel/config/usb_gadget/$UDC/functions/$GADGET"
    fi

    if [ ! -e "/sys/kernel/config/usb_gadget/$UDC/configs/r.1/$GADGET" ];
    then
        ln -s "/sys/kernel/config/usb_gadget/$UDC/functions/$GADGET" "/sys/kernel/config/usb_gadget/$UDC/configs/r.1/$GADGET"
    fi
}

function_stop()
{
    case "$MODE" in
        adbd)
            local GADGET="ffs.adb"
            ;;
        usbnet)
            local GADGET="ecm.usb0"
            ;;
    esac

    if [ -e "/sys/kernel/config/usb_gadget/$UDC/configs/r.1/$GADGET" ];
    then
        rm "/sys/kernel/config/usb_gadget/$UDC/configs/r.1/$GADGET"
    fi

    if [ -e "/sys/kernel/config/usb_gadget/$UDC/functions/$GADGET" ];
    then
        rmdir "/sys/kernel/config/usb_gadget/$UDC/functions/$GADGET"
    fi
    if [ -n "$(find "/sys/kernel/config/usb_gadget/$UDC/functions" -maxdepth 0 -type d -empty)" ];
    then
        echo "Unregister: /sys/kernel/config/usb_gadget/$UDC"
        rmdir "/sys/kernel/config/usb_gadget/$UDC/configs/r.1/strings/0x409"
        rmdir "/sys/kernel/config/usb_gadget/$UDC/configs/r.1"
        rmdir "/sys/kernel/config/usb_gadget/$UDC/strings/0x409"
        rmdir "/sys/kernel/config/usb_gadget/$UDC"
    else
        echo "$UDC" > "/sys/kernel/config/usb_gadget/$UDC/UDC" || true
    fi
}

start()
{
    configfs_init
    function_init

    case "$MODE" in
        adbd)
            if [ ! -e "/dev/usb-ffs/adb" ] ;
            then
                mkdir -p /dev/usb-ffs/adb
                mount -o uid=2000,gid=2000 -t functionfs adb /dev/usb-ffs/adb
            fi
            export service_adb_tcp_port=5555
            start-stop-daemon --start --oknodo --pidfile /var/run/adbd.pid --startas /usr/bin/adbd --background
            sleep 1
            ;;
    esac

    if [ -z "$UDC" ]; 
    then
        echo "No USB Device Controller was detected. Did you set your OTG port to host mode?"
        exit 1
    fi

    if [[ ! $(< "/sys/kernel/config/usb_gadget/$UDC/UDC") == "" ]] ;
    then
        echo "Unregister: /sys/kernel/config/usb_gadget/$UDC/UDC"
        echo "" > "/sys/kernel/config/usb_gadget/$UDC/UDC" 
    fi
    sleep 1
    echo "$UDC" > "/sys/kernel/config/usb_gadget/$UDC/UDC" || true
}

stop()
{
    function_stop
    case "$MODE" in
        adbd)
            killall adbd
            # start-stop-daemon --stop --oknodo --pidfile /var/run/adbd.pid --retry 5
            umount /dev/usb-ffs/adb
            rmdir /dev/usb-ffs/adb
            rmdir /dev/usb-ffs
            ;;
    esac
}

MODE="$1"
UDC="$3"
case "$2" in
start)
    start
    ;;
stop)
    stop
    ;;
restart|reload)
    stop
    start
    ;;
*)
    echo "Usage: $0 <adbd|usbnet> <start|stop|restart> <UDC>"
    exit 1
esac

exit 0
